### ISSUE TITLE
Unhandled exception while calling getMimeType()

### ISSUE THREAD

**Issue by crawter** [Storj/android-libstorj#24]
When we create instance of  storj.libstorj.File class getMimeType() method sometimes throws an unhandled exception at this line:

String mime = URLConnection.guessContentTypeFromName(name);

Example of such file:
http://dropmefiles.com/xDfzp

Steps to reproduce
1. upload this file to bucket
2. try to retrieve files list of this bucket and call getMimeType() method for this one

**Comment by kaloyan-raev** [comment]
Could you include the exception stack trace here?

**Comment by crawter** [comment]
FATAL EXCEPTION: Thread-25
                                                                 Process: com.storjmobile, PID: 21943
                                                                 java.lang.StringIndexOutOfBoundsException: String index out of range: -4
                                                                     at java.lang.String.substring(String.java:1975)
                                                                     at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
                                                                     at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:1381)
                                                                     at io.storj.libstorj.File.getMimeType(File.java:179)
                                                                     at storjlib.Models.FileModel.<init>(FileModel.java:86)
                                                                     at storjlib.Models.FileModel.<init>(FileModel.java:64)
                                                                     at storjlib.services.UploadService$1.onComplete(UploadService.java:166)
                                                                     at io.storj.libstorj.Storj._runEventLoop(Native Method)
                                                                     at io.storj.libstorj.Storj.access$100(Storj.java:29)
                                                                     at io.storj.libstorj.Storj$4.run(Storj.java:1238)
